### ISSUE TITLE
Editor window does not apply theme

### ISSUE THREAD

**Issue by sbszcz** [rmehri01/onenord-jetbrains#13]
Hello there,

many thanks for this theme it's my daily driver!

After the last update my editor windows won't apply the theme. I have attached a screenshot. I am currently running IntelliJ Idea  Build #IU-232.9559.62, built on August 23, 2023 with OneNord 0.0.7 on  KDE Plasma 5.27.7 with X11 (I don't know if this might be relevant).

I already tried switching between classic and new UI and switching to another theme. Unfortunately without success.

![Screenshot_20230905_084943](https://github.com/rmehri01/onenord-jetbrains/assets/2794784/52037d59-97a7-46e6-92c7-9bd52739f157)

Maybe you could help me with that issue?

Many Thanks,
Sebastian

**Comment by sbszcz** [comment]
Many thanks that fixed it!!!

**Comment by rmehri01** [comment]
No problem!
