### ISSUE TITLE
Datagrip table view isn't themed

### ISSUE THREAD

**Issue by Hazmi35** [rmehri01/onenord-jetbrains#16]
![image](https://github.com/rmehri01/onenord-jetbrains/assets/32807631/3b527612-80ff-4a0d-8405-9d87230f2efa)

System Info: DataGrip, on Windows 11 with OneNord 0.1.1.

**Comment by rmehri01** [comment]
Hi! I can't seem to reproduce this locally, would you happen to know if this is the same issue as #12 or #13? (try Settings > Editor > Color Scheme and see if it got set to the Classic Light editor theme instead of OneNord)

**Comment by Hazmi35** [comment]
> Hi! I can't seem to reproduce this locally, would you happen to know if this is the same issue as #12 or #13? (try Settings > Editor > Color Scheme and see if it got set to the Classic Light editor theme instead of OneNord)

Ah I see, didn't see that. Thanks!

**Comment by rmehri01** [comment]
No problem! Sorry about this, I'm still not sure how to fix it and couldn't get a response from JetBrains so I'm not sure if it is just an editor thing because some themes have the same issue and some don't
