### ISSUE TITLE
Version 0.1.2 white background

### ISSUE THREAD

**Issue by T3kla** [rmehri01/onenord-jetbrains#20]
Just updated to the last version and the background became white.

![image](https://github.com/rmehri01/onenord-jetbrains/assets/23636548/c356a3e7-2d2e-4de4-9be7-d8707394d0d2)

**Comment by rmehri01** [comment]
Hi, this might be the same issue as #12 or #13? (try Settings > Editor > Color Scheme and see if it got set to the Classic Light editor theme instead of OneNord)

**Comment by T3kla** [comment]
Yep, looks like the color scheme changes to be white. Saving another color scheme, closing, then selecting OneNord again does the trick.
