### ISSUE TITLE
Incompatible with 2024.2 IDEs 

### ISSUE THREAD

**Issue by stdStudent** [rmehri01/onenord-jetbrains#21]
I really enjoy this theme, but it's not listed as an available plugin for the Android Studio Ladybug.

On the plugin webpage I get this error:
![image](https://github.com/user-attachments/assets/1ec88c1c-c16a-42c6-a306-d9bc43d27084)

**Comment by rohlandm** [comment]
Same for Intellij Ultimate - it seems like it is not compatible with the 2024.2 yet

**Comment by rmehri01** [comment]
Ah sorry, I was on vacation so I didn't get around to updating this :sweat_smile:

**Comment by rmehri01** [comment]
This should be fixed now!
