### ISSUE TITLE
Compatibility with IntelliJ 2023.1

### ISSUE THREAD

**Issue by rohlandm** [rmehri01/onenord-jetbrains#7]
Good local time!

First and foremost, this theme is amazing, great work! 

Intellij 2023.1 was released today, and the Plugin is currently not supported anymore. I will probably adjust the property locally tomorrow (living in CEST) and open a PR, but I never worked with Jetbrains themes before :)

**Comment by rmehri01** [comment]
Hey, thanks, I'm glad you like the theme!

Sorry about that, I should have been keeping up with the release schedule better. I'll make the change ASAP and hopefully it will be updated on the marketplace in 1-2 days.

**Comment by rohlandm** [comment]
Thanks a lot 🚀

**Comment by rohlandm** [comment]
Just updated via the market place, thanks :)
